# This file was generated by go2nix.
{ stdenv, buildGoPackage, fetchFromGitHub }:

buildGoPackage rec {
  name = "minikube-${version}";
  version = "20160905-${stdenv.lib.strings.substring 0 7 rev}";
  rev = "a8f7477130ff793882df6f5479326e109f001c7b";

  goPackagePath = "k8s.io/minikube";
  subPackages = [ "./cmd" ];

  src = fetchFromGitHub {
    inherit rev;
    owner = "kubernetes";
    repo = "minikube";
    sha256 = "1q8gm14hk0w2sppbn2q9nliyb317qw8vw1ksmx1b5glrk5c6mcdl";
  };

  meta = with stdenv.lib; {
    description = "Run Kubernetes locally";
    license = licenses.asl20;
    homepage = https://kubernetes.io/docs/getting-started-guides/minikube/;
    maintainers = with maintainers; [offline];
    platforms = [ "x86_64-linux" ];
  };
}
