# This file was generated by go2nix.
{ stdenv, buildGoPackage, fetchgit }:

buildGoPackage rec {
  name = "minikube-${version}";
  version = "20160905-${stdenv.lib.strings.substring 0 7 rev}";
  rev = "a8f7477130ff793882df6f5479326e109f001c7b";

  goPackagePath = "k8s.io/minikube";

  src = fetchFromGitHub {
    inherit rev;
    owner = "k8s.io";
    repo = "minikube";
    sha256 = "1kzwcyh4v5s0x976dn3irpln7pfp6fz4zbzc8r0hsp73ry2lqrpi";
  };

  meta = with stdenv.lib; {
    description = "Run Kubernetes locally";
    license = licenses.asl20;
    homepage = https://kubernetes.io/docs/getting-started-guides/minikube/;
    maintainers = with maintainers; [offline];
    platforms = [ "x86_64-linux" ];
  };
}
